project_id = "pvhymyhsawelopclpdke"

[functions.sync-canvas-feed]
verify_jwt = false

[functions.debug-canvas-feed]
verify_jwt = false

[functions.sync-google-calendar]
verify_jwt = true

[functions.spotify-now-playing]
verify_jwt = true

[functions.store-spotify-connection]
verify_jwt = true

[functions.link-spotify-connection]
verify_jwt = true

[functions.moderate-content]
verify_jwt = true

[functions.ai-create-event]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.create-promotion]
verify_jwt = true

[functions.moderate-promotion]
verify_jwt = true